rllib changes to enable storing user_data in params.json
cathywu/ray pull request #2
Opened 2018-01-04 22:17 UTC by nskh

## What do these changes do?

Modified rllib to allow `params.json` to store a dict of `user_data` by making tweaks to the PPO and DQN algorithms. Also fixed two typos. Changes to `.gitignore` and `result.py` can be excluded.

2018-01-04 22:53 UTC, cathywu requested changes

2018-01-04 22:53 UTC, cathywu commented on .gitignore
> +# Ray results should be ignored
Please remove. `ray_results` does not default to being written inside the `ray` directory (as far as I know?).

2018-01-04 22:53 UTC, cathywu commented on python/ray/rllib/dqn/dqn.py
> +    user_data={})
Please add a comment.

2018-01-04 22:53 UTC, cathywu commented on python/ray/rllib/eval.py
> +        "of a built-in algorithm (e.g. RLLib's DQN or PPO), or a "
Nice :)

2018-01-04 22:53 UTC, cathywu commented on python/ray/rllib/ppo/ppo.py
> +    "user_data": {}
Again, please add a comment

2018-01-04 22:53 UTC, cathywu commented on python/ray/tune/result.py
> +DEFAULT_RESULTS_DIR = os.path.expanduser("~/Development/research/ray/ray_results")
Please don't include this change.

2018-01-04 22:54 UTC, cathywu commented
Yay, I like this clean solution. I just left some cleanup comments.

2018-01-05 02:15 UTC, nskh commented
Updated in accordance with your requested changes; should be good to go.

2018-01-05 07:22 UTC, cathywu approved these changes

2018-01-05 07:23 UTC, merged